apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-react
spec:
  template:
    spec:
      containers:
      - name: hello-react
        env:
        - name: ENVIRONMENT
          value: dev
