apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-react
spec:
  template:
    spec:
      containers:
      - name: hello-react
        image: 172.30.1.1:5000/dev/hello-react:latest-dev
        env:
        - name: ENVIRONMENT
          value: dev
