apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        image: 172.30.1.1:5000/dev/hello-react:latest-dev
        env:
        - name: ENVIRONMENT
          value: dev
