apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: dev/hello-react
  newTag: 960c79f98b95433013834195170561b44294dc3a
resources:
- ../base
