apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 172.30.1.1:5000/dev/hello-react
  newTag: latest
- name: dev/hello-react
  newTag: 503ed6019f64f0dd36c9cfa1c5f692630ab64109
resources:
- ../base
