apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 172.30.1.1:5000/dev/hello-react
  newTag: 960c79f98b95433013834195170561b44294dc3a
- name: dev/hello-react
  newTag: b3a7c9a595757f6c00597cb850d03f1d18abe818
resources:
- ../base
