apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-react
spec:
  replicas: 2
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: hello-react
  template:
    metadata:
      labels:
        app: hello-react
    spec:
      containers:
      - image: 172.30.1.1:5000/dev/hello-react:latest
        name: hello-react
        ports:
        - containerPort: 8081
