apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-react
  name: hello-react
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: hello-react
  type: LoadBalancer